# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d98646fa2374919ed5f8fe345352c76cdb44dbd14cc0346dca255d15374087faaa4a846912666ce523deeed0b4ec821f31054d5dba9af41b8f0b48f03feea5c9

test:
  secret_key_base: 8ca9c8150580f7bbae717a8dca846655257dbea2491b70aa9723ecb996598d3f430f1c4ab6e4b318fdc98a090c687508c3eb6c3b0ef44286f44c572174941cf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
